# Generated by Django 4.2.1 on 2023-05-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tablish',
            options={'verbose_name': 'Воспоминание', 'verbose_name_plural': 'Воспоминания'},
        ),
        migrations.RenameField(
            model_name='tablish',
            old_name='date_memory_publish',
            new_name='date',
        ),
    ]
