# Generated by Django 4.2.1 on 2023-05-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_tablish_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablish',
            name='title',
            field=models.CharField(default='Воспоминание', max_length=50, verbose_name='Название места'),
        ),
    ]
